/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.era.views.dialogs;

import com.era.utilities.DialogPropertiesUitlity;
import com.era.views.BaseJFrame;
import java.util.Properties;

/**
 *
 * @author PC
 */
public class ErrorDialogJFrame extends BaseJFrame {

    private OnOkButtonActionPerformed OnOkButtonActionPerformed;
    final Properties props;
    
    /**
     * Creates new form ErrorDialogJFrame
     * @throws java.lang.Exception
     */
    public ErrorDialogJFrame() throws Exception {
        
        this.props = DialogPropertiesUitlity.getSingleton().getProperties();
        
        initComponents();
        
        //Set window tittle
        final String finalString = props.getProperty("system_dialog_title");
        this.setTitle(finalString);
        
        okButton.addActionListener((java.awt.event.ActionEvent evt) -> {
            okButtonActionPerformed(evt);
        });
    }
    
    public void setText(final String idText) {
        final String finalString = props.getProperty(idText);
        this.mainText.setText(finalString);
    }
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if(OnOkButtonActionPerformed != null){
            OnOkButtonActionPerformed.okButtonActionPerformed(evt);
        }     
    }

    public void setOnOkButtonActionPerformed(OnOkButtonActionPerformed OnOkButtonActionPerformed) {
        this.OnOkButtonActionPerformed = OnOkButtonActionPerformed;
    }        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public interface OnOkButtonActionPerformed {
        void okButtonActionPerformed(java.awt.event.ActionEvent evt);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottomPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainText = new javax.swing.JTextArea();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bottomPanel.setBackground(new java.awt.Color(255, 255, 255));
        bottomPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(bottomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 392, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        mainText.setEditable(false);
        mainText.setColumns(20);
        mainText.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 13)); // NOI18N
        mainText.setLineWrap(true);
        mainText.setRows(5);
        mainText.setBorder(null);
        jScrollPane1.setViewportView(mainText);

        okButton.setText("OK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okButton)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mainText;
    protected javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
