/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.era.views;

public abstract class EmpresasJFrame extends BaseJFrame {

    protected final javax.swing.ButtonGroup bgMetodoCosteo;
    protected final javax.swing.ButtonGroup bgTipoContribuyente;
    
    public EmpresasJFrame(final String idTextTitleWindow) {
        
        super(idTextTitleWindow);
        
        initComponents();
               
        postInitComponents();
        
        bgMetodoCosteo  = new javax.swing.ButtonGroup();
        bgMetodoCosteo.add(JRBPEPS);
        bgMetodoCosteo.add(JRBUEPS);
        bgMetodoCosteo.add(JRBPromedio);
        bgMetodoCosteo.add(JRBUltCost);
        
        bgTipoContribuyente = new javax.swing.ButtonGroup();
        bgTipoContribuyente.add(JRBFisica);
        bgTipoContribuyente.add(JRBMoral);
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PNLBusqueda = new javax.swing.JPanel();
        PNLCampos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        JTIdEmpresa = new javax.swing.JTextField();
        JTCodigoEmpresa = new javax.swing.JTextField();
        JTEmpresa = new javax.swing.JTextField();
        JTBaseDeDatos = new javax.swing.JTextField();
        JTRFC = new javax.swing.JTextField();
        JTTelefono = new javax.swing.JTextField();
        JTCalle = new javax.swing.JTextField();
        JTNoExt = new javax.swing.JTextField();
        JTNoInt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTColonia = new javax.swing.JTextField();
        JTCiudad = new javax.swing.JTextField();
        JTEstado = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        JTCP = new javax.swing.JTextField();
        JTPais = new javax.swing.JTextField();
        JTCorreoElectronico = new javax.swing.JTextField();
        JTSitioWeb = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JTLugarDeExpedicion = new javax.swing.JTextField();
        JTRegimenFiscal = new javax.swing.JTextField();
        JTRutaKey = new javax.swing.JTextField();
        JTRutaAplicacion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        JTFechaAlta = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        JTFechaModificacion = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        JTRutaCertificado = new javax.swing.JTextField();
        JRBMoral = new javax.swing.JRadioButton();
        JRBFisica = new javax.swing.JRadioButton();
        JRBPEPS = new javax.swing.JRadioButton();
        JRBUEPS = new javax.swing.JRadioButton();
        JRBUltCost = new javax.swing.JRadioButton();
        JRBPromedio = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        JTExtTel = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        JTPlantilla = new javax.swing.JTextField();
        PNLAcciones = new javax.swing.JPanel();
        BTNLimpiarCampos = new javax.swing.JButton();
        BTNNuevaEmpresa = new javax.swing.JButton();
        BTNActualiza = new javax.swing.JButton();
        BTNBorraPorId = new javax.swing.JButton();
        BTNRespalda = new javax.swing.JButton();
        BTNRestaura = new javax.swing.JButton();
        BTNCargaRegimenFiscal = new javax.swing.JButton();
        BTNCargaCDS = new javax.swing.JButton();
        BTNCargaLugarExpedicion = new javax.swing.JButton();
        BTNCargaKey = new javax.swing.JButton();
        BTNPruebaPW = new javax.swing.JButton();
        JTPasswordCertificado = new javax.swing.JPasswordField();
        btnRutaAplicacion = new javax.swing.JButton();
        BTNPlantilla = new javax.swing.JButton();
        BTNCargaPais = new javax.swing.JButton();
        BTNCodigoPostal = new javax.swing.JButton();
        jSImg1 = new javax.swing.JScrollPane();
        jPanImg1 = new javax.swing.JPanel();
        jLImg = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBCargImg = new javax.swing.JButton();
        jBDelImg = new javax.swing.JButton();
        JPTabla = new javax.swing.JScrollPane();
        jTabEmpresas = new com.era.views.tables.BasDatsTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Empresa");
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 800));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Empresas");

        PNLBusqueda.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PNLBusquedaLayout = new javax.swing.GroupLayout(PNLBusqueda);
        PNLBusqueda.setLayout(PNLBusquedaLayout);
        PNLBusquedaLayout.setHorizontalGroup(
            PNLBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        PNLBusquedaLayout.setVerticalGroup(
            PNLBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PNLCampos.setBackground(new java.awt.Color(255, 255, 255));
        PNLCampos.setToolTipText("");

        jLabel2.setText("ID");

        jLabel3.setText("Código");

        jLabel4.setText("* Empresa");

        jLabel6.setText("* Base de Datos");

        jLabel12.setText("Teléfono");

        jLabel10.setText("* Calle");

        jLabel8.setText("* No Ext");

        jLabel9.setText("No Int");

        jLabel13.setText("* Ciudad");

        jLabel14.setText("* Estado");

        jLabel15.setText("Correo electronico");

        jLabel16.setText("* Pais");

        jLabel17.setText("* RFC");

        jLabel21.setText("Lugar de Expedición");

        jLabel22.setText("Regimen Fiscal");

        jLabel23.setText("* CP");

        jLabel24.setText("CDS .cer");

        jLabel25.setText("CFD .key");

        jLabel26.setText("CDS Contraseña");

        JTIdEmpresa.setEditable(false);
        JTIdEmpresa.setNextFocusableComponent(JTCodigoEmpresa);

        JTCodigoEmpresa.setNextFocusableComponent(JTEmpresa);

        JTEmpresa.setNextFocusableComponent(JTBaseDeDatos);

        JTBaseDeDatos.setNextFocusableComponent(JTRFC);

        JTRFC.setNextFocusableComponent(JTTelefono);

        JTTelefono.setNextFocusableComponent(JTExtTel);

        JTCalle.setNextFocusableComponent(JTNoExt);

        JTNoExt.setNextFocusableComponent(JTNoInt);

        JTNoInt.setNextFocusableComponent(JTColonia);

        jLabel7.setText("* Colonia");

        JTColonia.setNextFocusableComponent(JTCiudad);

        JTCiudad.setNextFocusableComponent(JTEstado);

        JTEstado.setNextFocusableComponent(JTCP);

        jLabel18.setText("Sitio WEB");

        JTCP.setNextFocusableComponent(JTPais);

        JTPais.setNextFocusableComponent(JTCorreoElectronico);

        JTCorreoElectronico.setNextFocusableComponent(JTSitioWeb);

        JTSitioWeb.setNextFocusableComponent(JRBMoral);

        jLabel11.setText("Ruta Aplicación");

        JTLugarDeExpedicion.setNextFocusableComponent(JTRegimenFiscal);

        JTRegimenFiscal.setNextFocusableComponent(JTRutaCertificado);

        JTRutaKey.setNextFocusableComponent(JTPasswordCertificado);

        JTRutaAplicacion.setNextFocusableComponent(JTPlantilla);

        jLabel19.setText("Fecha Alta");

        JTFechaAlta.setEditable(false);
        JTFechaAlta.setNextFocusableComponent(JTFechaModificacion);
        JTFechaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFechaAltaActionPerformed(evt);
            }
        });

        jLabel29.setText("Fecha Modificación");

        JTFechaModificacion.setEditable(false);
        JTFechaModificacion.setNextFocusableComponent(JRBPEPS);

        jLabel27.setText("Tipo Contribuyente");

        jLabel28.setText("Método Costeo");

        JTRutaCertificado.setNextFocusableComponent(JTRutaKey);

        JRBMoral.setSelected(true);
        JRBMoral.setText("Moral");
        JRBMoral.setNextFocusableComponent(JRBFisica);

        JRBFisica.setText("Física");

        JRBPEPS.setSelected(true);
        JRBPEPS.setText("PEPS");
        JRBPEPS.setNextFocusableComponent(JRBUEPS);

        JRBUEPS.setText("UEPS");
        JRBUEPS.setNextFocusableComponent(JRBUltCost);

        JRBUltCost.setText("Ult Cost");
        JRBUltCost.setNextFocusableComponent(JRBPromedio);

        JRBPromedio.setText("Promedio");
        JRBPromedio.setNextFocusableComponent(BTNLimpiarCampos);

        jLabel30.setText("Ext");

        JTExtTel.setNextFocusableComponent(JTCalle);

        jLabel33.setText("Plantilla");

        JTPlantilla.setNextFocusableComponent(JTFechaAlta);

        BTNLimpiarCampos.setBackground(new java.awt.Color(255, 255, 255));
        BTNLimpiarCampos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNLimpiarCampos.setForeground(new java.awt.Color(0, 102, 0));
        BTNLimpiarCampos.setText("Limpiar Campos");
        BTNLimpiarCampos.setAutoscrolls(true);
        BTNLimpiarCampos.setNextFocusableComponent(BTNNuevaEmpresa);
        BTNLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLimpiarCamposActionPerformed(evt);
            }
        });

        BTNNuevaEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        BTNNuevaEmpresa.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNNuevaEmpresa.setForeground(new java.awt.Color(0, 102, 0));
        BTNNuevaEmpresa.setText("Agregar Empresa");
        BTNNuevaEmpresa.setNextFocusableComponent(BTNActualiza);
        BTNNuevaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNNuevaEmpresaActionPerformed(evt);
            }
        });

        BTNActualiza.setBackground(new java.awt.Color(255, 255, 255));
        BTNActualiza.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNActualiza.setForeground(new java.awt.Color(0, 102, 0));
        BTNActualiza.setText("Actualizar");
        BTNActualiza.setNextFocusableComponent(BTNBorraPorId);
        BTNActualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNActualizaActionPerformed(evt);
            }
        });

        BTNBorraPorId.setBackground(new java.awt.Color(255, 255, 255));
        BTNBorraPorId.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNBorraPorId.setForeground(new java.awt.Color(0, 102, 0));
        BTNBorraPorId.setText("Borrar");
        BTNBorraPorId.setNextFocusableComponent(BTNRespalda);
        BTNBorraPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBorraPorIdActionPerformed(evt);
            }
        });

        BTNRespalda.setBackground(new java.awt.Color(255, 255, 255));
        BTNRespalda.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNRespalda.setForeground(new java.awt.Color(0, 102, 0));
        BTNRespalda.setText("Respaldar");
        BTNRespalda.setNextFocusableComponent(BTNRestaura);
        BTNRespalda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRespaldaActionPerformed(evt);
            }
        });

        BTNRestaura.setBackground(new java.awt.Color(255, 255, 255));
        BTNRestaura.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNRestaura.setForeground(new java.awt.Color(0, 102, 0));
        BTNRestaura.setText("Restaura");
        BTNRestaura.setNextFocusableComponent(JTIdEmpresa);

        javax.swing.GroupLayout PNLAccionesLayout = new javax.swing.GroupLayout(PNLAcciones);
        PNLAcciones.setLayout(PNLAccionesLayout);
        PNLAccionesLayout.setHorizontalGroup(
            PNLAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNLimpiarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNNuevaEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNActualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNBorraPorId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNRespalda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNRestaura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNLAccionesLayout.setVerticalGroup(
            PNLAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLAccionesLayout.createSequentialGroup()
                .addComponent(BTNLimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNNuevaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNActualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNBorraPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNRespalda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNRestaura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        BTNCargaRegimenFiscal.setText("jButton2");
        BTNCargaRegimenFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCargaRegimenFiscalActionPerformed(evt);
            }
        });

        BTNCargaCDS.setText("jButton3");
        BTNCargaCDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCargaCDSActionPerformed(evt);
            }
        });

        BTNCargaLugarExpedicion.setText("jButton4");
        BTNCargaLugarExpedicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCargaLugarExpedicionActionPerformed(evt);
            }
        });

        BTNCargaKey.setText("jButton5");
        BTNCargaKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCargaKeyActionPerformed(evt);
            }
        });

        BTNPruebaPW.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNPruebaPW.setText("Probar");
        BTNPruebaPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPruebaPWActionPerformed(evt);
            }
        });

        btnRutaAplicacion.setText("jButton1");
        btnRutaAplicacion.setName(""); // NOI18N
        btnRutaAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaAplicacionActionPerformed(evt);
            }
        });

        BTNPlantilla.setText("jButton1");
        BTNPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPlantillaActionPerformed(evt);
            }
        });

        BTNCargaPais.setText("jButton1");
        BTNCargaPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCargaPaisActionPerformed(evt);
            }
        });

        BTNCodigoPostal.setText("jButton1");
        BTNCodigoPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCodigoPostalActionPerformed(evt);
            }
        });

        jSImg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSImg1KeyPressed(evt);
            }
        });

        jPanImg1.setBackground(new java.awt.Color(255, 255, 204));
        jPanImg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanImg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanImg1MouseExited(evt);
            }
        });
        jPanImg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanImg1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanImg1Layout = new javax.swing.GroupLayout(jPanImg1);
        jPanImg1.setLayout(jPanImg1Layout);
        jPanImg1Layout.setHorizontalGroup(
            jPanImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanImg1Layout.createSequentialGroup()
                .addComponent(jLImg)
                .addGap(0, 141, Short.MAX_VALUE))
        );
        jPanImg1Layout.setVerticalGroup(
            jPanImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanImg1Layout.createSequentialGroup()
                .addComponent(jLImg)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jSImg1.setViewportView(jPanImg1);

        jLabel5.setText("Logotipo");

        jBCargImg.setBackground(new java.awt.Color(255, 255, 255));
        jBCargImg.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jBCargImg.setText("Cargar");
        jBCargImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBCargImgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBCargImgMouseExited(evt);
            }
        });
        jBCargImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCargImgActionPerformed(evt);
            }
        });
        jBCargImg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBCargImgKeyPressed(evt);
            }
        });

        jBDelImg.setBackground(new java.awt.Color(255, 255, 255));
        jBDelImg.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jBDelImg.setText("Borrar");
        jBDelImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBDelImgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBDelImgMouseExited(evt);
            }
        });
        jBDelImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDelImgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNLCamposLayout = new javax.swing.GroupLayout(PNLCampos);
        PNLCampos.setLayout(PNLCamposLayout);
        PNLCamposLayout.setHorizontalGroup(
            PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNLCamposLayout.createSequentialGroup()
                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNLCamposLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addGap(237, 237, 237))
                            .addGroup(PNLCamposLayout.createSequentialGroup()
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel4)
                                    .addComponent(JTCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(PNLCamposLayout.createSequentialGroup()
                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNLCamposLayout.createSequentialGroup()
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10))
                                .addGap(9, 9, 9)
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PNLCamposLayout.createSequentialGroup()
                                        .addComponent(JTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JTExtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JTCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PNLCamposLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(JTEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PNLCamposLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(43, 43, 43)
                                .addComponent(JTColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PNLCamposLayout.createSequentialGroup()
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel23))
                                .addGap(45, 45, 45)
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(JTCodigoEmpresa)
                                        .addComponent(JTEmpresa)
                                        .addComponent(JTCiudad)
                                        .addGroup(PNLCamposLayout.createSequentialGroup()
                                            .addComponent(JTNoExt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(JTNoInt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(JTIdEmpresa))
                                    .addGroup(PNLCamposLayout.createSequentialGroup()
                                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JTPais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JTCP, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BTNCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BTNCargaPais, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(JTSitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNLCamposLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(47, 47, 47)
                        .addComponent(JTFechaAlta))
                    .addGroup(PNLCamposLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(35, 35, 35)
                        .addComponent(JRBMoral)
                        .addGap(18, 18, 18)
                        .addComponent(JRBFisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PNLCamposLayout.createSequentialGroup()
                            .addGap(85, 85, 85)
                            .addComponent(jLabel28)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JTFechaModificacion)
                                .addGroup(PNLCamposLayout.createSequentialGroup()
                                    .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JRBPromedio)
                                        .addComponent(JRBUltCost)
                                        .addComponent(JRBUEPS)
                                        .addComponent(JRBPEPS))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                    .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addGroup(PNLCamposLayout.createSequentialGroup()
                                            .addComponent(jBCargImg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jBDelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(19, 19, 19))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLCamposLayout.createSequentialGroup()
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(215, 215, 215)))
                    .addGroup(PNLCamposLayout.createSequentialGroup()
                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PNLCamposLayout.createSequentialGroup()
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PNLCamposLayout.createSequentialGroup()
                                        .addComponent(JTRutaAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRutaAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PNLCamposLayout.createSequentialGroup()
                                        .addComponent(JTPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTNPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PNLCamposLayout.createSequentialGroup()
                                        .addComponent(JTRutaCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTNCargaCDS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PNLCamposLayout.createSequentialGroup()
                                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(JTRegimenFiscal)
                                            .addComponent(JTLugarDeExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BTNCargaLugarExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BTNCargaRegimenFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLCamposLayout.createSequentialGroup()
                                            .addComponent(JTPasswordCertificado)
                                            .addGap(18, 18, 18)
                                            .addComponent(BTNPruebaPW))
                                        .addGroup(PNLCamposLayout.createSequentialGroup()
                                            .addComponent(JTRutaKey, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BTNCargaKey, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26)
                .addComponent(PNLAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PNLCamposLayout.setVerticalGroup(
            PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLCamposLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTIdEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(JRBMoral)
                    .addComponent(JRBFisica))
                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PNLCamposLayout.createSequentialGroup()
                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNLCamposLayout.createSequentialGroup()
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(JTCodigoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(JTEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(JTBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(JTRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(JTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30)
                                    .addComponent(JTExtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(JTCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(JTNoExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9)
                                        .addComponent(JTNoInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JTColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(PNLCamposLayout.createSequentialGroup()
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PNLCamposLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(JTRegimenFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BTNCargaRegimenFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(JTRutaCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BTNCargaCDS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel25)
                                            .addComponent(JTRutaKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BTNCargaKey, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel26)
                                            .addComponent(BTNPruebaPW)
                                            .addComponent(JTPasswordCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(JTRutaAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnRutaAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel21)
                                        .addComponent(JTLugarDeExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BTNCargaLugarExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PNLCamposLayout.createSequentialGroup()
                                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JTPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BTNPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JTFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PNLCamposLayout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel19)))))
                        .addGap(18, 18, 18)
                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNLCamposLayout.createSequentialGroup()
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JTCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PNLCamposLayout.createSequentialGroup()
                                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(JTEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14))
                                        .addGap(9, 9, 9)
                                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel23)
                                            .addComponent(JTCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BTNCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(JTPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BTNCargaPais, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PNLCamposLayout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(PNLCamposLayout.createSequentialGroup()
                                                        .addComponent(jLabel15)
                                                        .addGap(3, 3, 3)
                                                        .addComponent(JTCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(PNLCamposLayout.createSequentialGroup()
                                                        .addGap(41, 41, 41)
                                                        .addComponent(jLabel18))))))
                                    .addGroup(PNLCamposLayout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addComponent(JTSitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PNLCamposLayout.createSequentialGroup()
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel29)
                                    .addComponent(JTFechaModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PNLCamposLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JRBPEPS)
                                            .addComponent(jLabel28))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JRBUEPS)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JRBUltCost)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JRBPromedio))
                                    .addGroup(PNLCamposLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PNLCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBCargImg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBDelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addComponent(PNLAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPTabla.setAutoscrolls(true);
        JPTabla.setPreferredSize(new java.awt.Dimension(1000, 400));

        jTabEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CódigoEmpresa", "Empresa", "Base de Datos", "Método Costeo", "Teléfono", "Ext", "Calle", "CP", "NoExt", "NoInt", "Colonia", "Ciudad", "Estado", "Pais", "RFC", "Correo", "Sucursal", "Caja", "Sitio Web", "Tipo Contribuyente", "Estación", "Lugar de Expedición", "Regimen Fiscal", "Ruta Certificado", "Ruta Key", "Password Certificado", "Ruta Aplicacion", "Plantilla", "Fecha Alta", "Fecha Modificacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTabEmpresas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTabEmpresas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JPTabla.setViewportView(jTabEmpresas);
        if (jTabEmpresas.getColumnModel().getColumnCount() > 0) {
            jTabEmpresas.getColumnModel().getColumn(0).setMinWidth(30);
            jTabEmpresas.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTabEmpresas.getColumnModel().getColumn(1).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(2).setMinWidth(250);
            jTabEmpresas.getColumnModel().getColumn(2).setPreferredWidth(250);
            jTabEmpresas.getColumnModel().getColumn(3).setMinWidth(250);
            jTabEmpresas.getColumnModel().getColumn(3).setPreferredWidth(250);
            jTabEmpresas.getColumnModel().getColumn(4).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(5).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(6).setMinWidth(30);
            jTabEmpresas.getColumnModel().getColumn(6).setPreferredWidth(30);
            jTabEmpresas.getColumnModel().getColumn(7).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(8).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(8).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(9).setMinWidth(50);
            jTabEmpresas.getColumnModel().getColumn(9).setPreferredWidth(50);
            jTabEmpresas.getColumnModel().getColumn(10).setMinWidth(50);
            jTabEmpresas.getColumnModel().getColumn(10).setPreferredWidth(50);
            jTabEmpresas.getColumnModel().getColumn(11).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(11).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(12).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(12).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(13).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(13).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(14).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(14).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(15).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(15).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(16).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(16).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(17).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(17).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(18).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(18).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(19).setMinWidth(200);
            jTabEmpresas.getColumnModel().getColumn(19).setPreferredWidth(200);
            jTabEmpresas.getColumnModel().getColumn(20).setMinWidth(50);
            jTabEmpresas.getColumnModel().getColumn(20).setPreferredWidth(50);
            jTabEmpresas.getColumnModel().getColumn(21).setMinWidth(50);
            jTabEmpresas.getColumnModel().getColumn(21).setPreferredWidth(50);
            jTabEmpresas.getColumnModel().getColumn(22).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(22).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(23).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(23).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(24).setMinWidth(200);
            jTabEmpresas.getColumnModel().getColumn(24).setPreferredWidth(200);
            jTabEmpresas.getColumnModel().getColumn(25).setMinWidth(200);
            jTabEmpresas.getColumnModel().getColumn(25).setPreferredWidth(200);
            jTabEmpresas.getColumnModel().getColumn(26).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(26).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(27).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(27).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(28).setMinWidth(200);
            jTabEmpresas.getColumnModel().getColumn(28).setPreferredWidth(200);
            jTabEmpresas.getColumnModel().getColumn(29).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(29).setPreferredWidth(100);
            jTabEmpresas.getColumnModel().getColumn(30).setMinWidth(100);
            jTabEmpresas.getColumnModel().getColumn(30).setPreferredWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PNLCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(PNLBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JPTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(JPTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PNLCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PNLBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPTabla.getAccessibleContext().setAccessibleParent(JPTabla);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNBorraPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBorraPorIdActionPerformed
                
    }//GEN-LAST:event_BTNBorraPorIdActionPerformed

    private void BTNActualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNActualizaActionPerformed
                
    }//GEN-LAST:event_BTNActualizaActionPerformed
       
    private void BTNNuevaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNNuevaEmpresaActionPerformed
                
    }//GEN-LAST:event_BTNNuevaEmpresaActionPerformed

    private void JTFechaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFechaAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFechaAltaActionPerformed

    private void BTNLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLimpiarCamposActionPerformed
        
    }//GEN-LAST:event_BTNLimpiarCamposActionPerformed

    private void BTNRespaldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRespaldaActionPerformed
        
    }//GEN-LAST:event_BTNRespaldaActionPerformed

    private void BTNCargaLugarExpedicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCargaLugarExpedicionActionPerformed
        
    }//GEN-LAST:event_BTNCargaLugarExpedicionActionPerformed

    private void BTNCargaRegimenFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCargaRegimenFiscalActionPerformed
        
    }//GEN-LAST:event_BTNCargaRegimenFiscalActionPerformed

    private void BTNCargaCDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCargaCDSActionPerformed
        
    }//GEN-LAST:event_BTNCargaCDSActionPerformed

    private void BTNCargaKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCargaKeyActionPerformed
        
    }//GEN-LAST:event_BTNCargaKeyActionPerformed

    private void BTNPruebaPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPruebaPWActionPerformed
        
        
    }//GEN-LAST:event_BTNPruebaPWActionPerformed

    private void BTNCodigoPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCodigoPostalActionPerformed
        
    }//GEN-LAST:event_BTNCodigoPostalActionPerformed

    private void BTNCargaPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCargaPaisActionPerformed
        
    }//GEN-LAST:event_BTNCargaPaisActionPerformed

    private void btnRutaAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaAplicacionActionPerformed
        
    }//GEN-LAST:event_btnRutaAplicacionActionPerformed

    private void BTNPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPlantillaActionPerformed
        
    }//GEN-LAST:event_BTNPlantillaActionPerformed

    private void jPanImg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanImg1MouseEntered
        
    }//GEN-LAST:event_jPanImg1MouseEntered

    private void jPanImg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanImg1MouseExited

    }//GEN-LAST:event_jPanImg1MouseExited

    private void jPanImg1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanImg1KeyPressed

    }//GEN-LAST:event_jPanImg1KeyPressed

    private void jSImg1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSImg1KeyPressed

    }//GEN-LAST:event_jSImg1KeyPressed

    private void jBCargImgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCargImgMouseEntered
        
    }//GEN-LAST:event_jBCargImgMouseEntered

    private void jBCargImgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCargImgMouseExited
        
    }//GEN-LAST:event_jBCargImgMouseExited

    private void jBCargImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCargImgActionPerformed

    }//GEN-LAST:event_jBCargImgActionPerformed

    private void jBCargImgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBCargImgKeyPressed

    }//GEN-LAST:event_jBCargImgKeyPressed

    private void jBDelImgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDelImgMouseEntered
        
    }//GEN-LAST:event_jBDelImgMouseEntered

    private void jBDelImgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDelImgMouseExited
        
    }//GEN-LAST:event_jBDelImgMouseExited

    private void jBDelImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDelImgActionPerformed
        
    }//GEN-LAST:event_jBDelImgActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton BTNActualiza;
    protected javax.swing.JButton BTNBorraPorId;
    protected javax.swing.JButton BTNCargaCDS;
    protected javax.swing.JButton BTNCargaKey;
    protected javax.swing.JButton BTNCargaLugarExpedicion;
    protected javax.swing.JButton BTNCargaPais;
    protected javax.swing.JButton BTNCargaRegimenFiscal;
    protected javax.swing.JButton BTNCodigoPostal;
    protected javax.swing.JButton BTNLimpiarCampos;
    protected javax.swing.JButton BTNNuevaEmpresa;
    protected javax.swing.JButton BTNPlantilla;
    protected javax.swing.JButton BTNPruebaPW;
    protected javax.swing.JButton BTNRespalda;
    protected javax.swing.JButton BTNRestaura;
    protected javax.swing.JScrollPane JPTabla;
    protected javax.swing.JRadioButton JRBFisica;
    protected javax.swing.JRadioButton JRBMoral;
    protected javax.swing.JRadioButton JRBPEPS;
    protected javax.swing.JRadioButton JRBPromedio;
    protected javax.swing.JRadioButton JRBUEPS;
    protected javax.swing.JRadioButton JRBUltCost;
    protected javax.swing.JTextField JTBaseDeDatos;
    protected javax.swing.JTextField JTCP;
    protected javax.swing.JTextField JTCalle;
    protected javax.swing.JTextField JTCiudad;
    protected javax.swing.JTextField JTCodigoEmpresa;
    protected javax.swing.JTextField JTColonia;
    protected javax.swing.JTextField JTCorreoElectronico;
    protected javax.swing.JTextField JTEmpresa;
    protected javax.swing.JTextField JTEstado;
    protected javax.swing.JTextField JTExtTel;
    protected javax.swing.JTextField JTFechaAlta;
    protected javax.swing.JTextField JTFechaModificacion;
    protected javax.swing.JTextField JTIdEmpresa;
    protected javax.swing.JTextField JTLugarDeExpedicion;
    protected javax.swing.JTextField JTNoExt;
    protected javax.swing.JTextField JTNoInt;
    protected javax.swing.JTextField JTPais;
    protected javax.swing.JPasswordField JTPasswordCertificado;
    protected javax.swing.JTextField JTPlantilla;
    protected javax.swing.JTextField JTRFC;
    protected javax.swing.JTextField JTRegimenFiscal;
    protected javax.swing.JTextField JTRutaAplicacion;
    protected javax.swing.JTextField JTRutaCertificado;
    protected javax.swing.JTextField JTRutaKey;
    protected javax.swing.JTextField JTSitioWeb;
    protected javax.swing.JTextField JTTelefono;
    private javax.swing.JPanel PNLAcciones;
    private javax.swing.JPanel PNLBusqueda;
    private javax.swing.JPanel PNLCampos;
    protected javax.swing.JButton btnRutaAplicacion;
    protected javax.swing.JButton jBCargImg;
    protected javax.swing.JButton jBDelImg;
    protected javax.swing.JLabel jLImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    protected javax.swing.JPanel jPanImg1;
    private javax.swing.JScrollPane jSImg1;
    protected com.era.views.tables.BasDatsTable jTabEmpresas;
    // End of variables declaration//GEN-END:variables
}
