/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.era.views;

public abstract class EmpresasJFrame extends BaseJFrame {

    protected final javax.swing.ButtonGroup bgMetodoCosteo;
    protected final javax.swing.ButtonGroup bgTipoContribuyente;
    
    public EmpresasJFrame(final String idTextTitleWindow) {
        
        super(idTextTitleWindow);
        
        initComponents();
               
        postInitComponents();
        
        bgMetodoCosteo  = new javax.swing.ButtonGroup();
        bgMetodoCosteo.add(JRBPEPS);
        bgMetodoCosteo.add(JRBUEPS);
        bgMetodoCosteo.add(JRBPromedio);
        bgMetodoCosteo.add(JRBUltCost);
        
        bgTipoContribuyente = new javax.swing.ButtonGroup();
        bgTipoContribuyente.add(JRBFisica);
        bgTipoContribuyente.add(JRBMoral);
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PNLBusqueda = new javax.swing.JPanel();
        PNLCampos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        JTIdEmpresa = new javax.swing.JTextField();
        JTCodigoEmpresa = new javax.swing.JTextField();
        JTEmpresa = new javax.swing.JTextField();
        JTBaseDeDatos = new javax.swing.JTextField();
        JTRFC = new javax.swing.JTextField();
        JTTelefono = new javax.swing.JTextField();
        JTCalle = new javax.swing.JTextField();
        JTNoExt = new javax.swing.JTextField();
        JTNoInt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTColonia = new javax.swing.JTextField();
        JTCiudad = new javax.swing.JTextField();
        JTEstado = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        JTCP = new javax.swing.JTextField();
        JTPais = new javax.swing.JTextField();
        JTCorreoElectronico = new javax.swing.JTextField();
        JTSitioWeb = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JTLugarDeExpedicion = new javax.swing.JTextField();
        JTRegimenFiscal = new javax.swing.JTextField();
        JTRutaKey = new javax.swing.JTextField();
        JTRutaAplicacion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        JTFechaAlta = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        JTFechaModificacion = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        JTRutaCertificado = new javax.swing.JTextField();
        JRBMoral = new javax.swing.JRadioButton();
        JRBFisica = new javax.swing.JRadioButton();
        JRBPEPS = new javax.swing.JRadioButton();
        JRBUEPS = new javax.swing.JRadioButton();
        JRBUltCost = new javax.swing.JRadioButton();
        JRBPromedio = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        JTExtTel = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        JTPlantilla = new javax.swing.JTextField();
        PNLAcciones = new javax.swing.JPanel();
        BTNLimpiarCampos = new javax.swing.JButton();
        BTNNuevaEmpresa = new javax.swing.JButton();
        BTNActualiza = new javax.swing.JButton();
        BTNBorraPorId = new javax.swing.JButton();
        BTNRespalda = new javax.swing.JButton();
        BTNRestaura = new javax.swing.JButton();
        BTNCargaRegimenFiscal = new javax.swing.JButton();
        BTNCargaCDS = new javax.swing.JButton();
        BTNCargaLugarExpedicion = new javax.swing.JButton();
        BTNCargaKey = new javax.swing.JButton();
        BTNPruebaPW = new javax.swing.JButton();
        JTPasswordCertificado = new javax.swing.JPasswordField();
        btnRutaAplicacion = new javax.swing.JButton();
        BTNPlantilla = new javax.swing.JButton();
        BTNCargaPais = new javax.swing.JButton();
        BTNCodigoPostal = new javax.swing.JButton();
        jPanImg1 = new javax.swing.JPanel();
        jLImg = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBCargImg = new javax.swing.JButton();
        jBDelImg = new javax.swing.JButton();
        JPTabla = new javax.swing.JScrollPane();
        jTabEmpresas = new com.era.views.tables.BasDatsTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Empresa");
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 800));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Empresas");

        PNLBusqueda.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PNLBusquedaLayout = new javax.swing.GroupLayout(PNLBusqueda);
        PNLBusqueda.setLayout(PNLBusquedaLayout);
        PNLBusquedaLayout.setHorizontalGroup(
            PNLBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        PNLBusquedaLayout.setVerticalGroup(
            PNLBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PNLCampos.setBackground(new java.awt.Color(255, 255, 255));
        PNLCampos.setToolTipText("");
        PNLCampos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID");
        PNLCampos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel3.setText("Código");
        PNLCampos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, -1, -1));

        jLabel4.setText("* Empresa");
        PNLCampos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, -1, -1));

        jLabel6.setText("* BD");
        PNLCampos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, 80, -1));

        jLabel12.setText("Teléfono");
        PNLCampos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel10.setText("* Calle");
        PNLCampos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, -1, -1));

        jLabel8.setText("* No Ext");
        PNLCampos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 189, -1, -1));

        jLabel9.setText("No Int");
        PNLCampos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 192, -1, -1));

        jLabel13.setText("* Ciudad");
        PNLCampos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 262, -1, -1));

        jLabel14.setText("* Estado");
        PNLCampos.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 282, 50, -1));

        jLabel15.setText("Correo electronico");
        PNLCampos.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel16.setText("* Pais");
        PNLCampos.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 325, -1, -1));

        jLabel17.setText("* RFC");
        PNLCampos.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 111, -1, -1));

        jLabel21.setText("Lugar de Expedición");
        PNLCampos.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 36, 126, -1));

        jLabel22.setText("Regimen Fiscal");
        PNLCampos.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 59, 105, -1));

        jLabel23.setText("* CP");
        PNLCampos.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 308, -1, -1));

        jLabel24.setText("CDS .cer");
        PNLCampos.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 85, 105, -1));

        jLabel25.setText("CFD .key");
        PNLCampos.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 114, 105, -1));

        jLabel26.setText("CDS Contraseña");
        PNLCampos.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 141, 105, -1));

        JTIdEmpresa.setEditable(false);
        JTIdEmpresa.setNextFocusableComponent(JTCodigoEmpresa);
        PNLCampos.add(JTIdEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 11, 178, -1));

        JTCodigoEmpresa.setNextFocusableComponent(JTEmpresa);
        PNLCampos.add(JTCodigoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 33, 178, -1));

        JTEmpresa.setNextFocusableComponent(JTBaseDeDatos);
        PNLCampos.add(JTEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 59, 178, -1));

        JTBaseDeDatos.setNextFocusableComponent(JTRFC);
        PNLCampos.add(JTBaseDeDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 85, 178, -1));

        JTRFC.setNextFocusableComponent(JTTelefono);
        PNLCampos.add(JTRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 111, 178, -1));

        JTTelefono.setNextFocusableComponent(JTExtTel);
        PNLCampos.add(JTTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 137, 87, -1));

        JTCalle.setNextFocusableComponent(JTNoExt);
        PNLCampos.add(JTCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 163, 178, -1));

        JTNoExt.setNextFocusableComponent(JTNoInt);
        PNLCampos.add(JTNoExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 189, 70, -1));

        JTNoInt.setNextFocusableComponent(JTColonia);
        PNLCampos.add(JTNoInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 189, 70, -1));

        jLabel7.setText("* Colonia");
        PNLCampos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 221, -1, -1));

        JTColonia.setNextFocusableComponent(JTCiudad);
        PNLCampos.add(JTColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 215, 178, -1));

        JTCiudad.setNextFocusableComponent(JTEstado);
        PNLCampos.add(JTCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 256, 178, -1));

        JTEstado.setNextFocusableComponent(JTCP);
        PNLCampos.add(JTEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 276, 178, -1));

        jLabel18.setText("Sitio WEB");
        PNLCampos.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 391, -1, -1));

        JTCP.setNextFocusableComponent(JTPais);
        PNLCampos.add(JTCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 305, 138, -1));

        JTPais.setNextFocusableComponent(JTCorreoElectronico);
        PNLCampos.add(JTPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 325, 138, -1));

        JTCorreoElectronico.setNextFocusableComponent(JTSitioWeb);
        PNLCampos.add(JTCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 367, 264, -1));

        JTSitioWeb.setNextFocusableComponent(JRBMoral);
        PNLCampos.add(JTSitioWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 405, 264, -1));

        jLabel11.setText("Ruta Aplicación");
        PNLCampos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 169, 105, -1));

        JTLugarDeExpedicion.setNextFocusableComponent(JTRegimenFiscal);
        PNLCampos.add(JTLugarDeExpedicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 33, 300, -1));

        JTRegimenFiscal.setNextFocusableComponent(JTRutaCertificado);
        PNLCampos.add(JTRegimenFiscal, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 59, 300, -1));

        JTRutaKey.setNextFocusableComponent(JTPasswordCertificado);
        PNLCampos.add(JTRutaKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 111, 300, -1));

        JTRutaAplicacion.setNextFocusableComponent(JTPlantilla);
        PNLCampos.add(JTRutaAplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 166, 300, -1));

        jLabel19.setText("Fecha Alta");
        PNLCampos.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 120, -1));

        JTFechaAlta.setEditable(false);
        JTFechaAlta.setNextFocusableComponent(JTFechaModificacion);
        JTFechaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFechaAltaActionPerformed(evt);
            }
        });
        PNLCampos.add(JTFechaAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 220, 200, 20));

        jLabel29.setText("Fecha Modificación");
        PNLCampos.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 120, -1));

        JTFechaModificacion.setEditable(false);
        JTFechaModificacion.setNextFocusableComponent(JRBPEPS);
        PNLCampos.add(JTFechaModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 250, 200, -1));

        jLabel27.setText("Tipo Contribuyente");
        PNLCampos.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 14, -1, -1));

        jLabel28.setText("Método Costeo");
        PNLCampos.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 130, 20));

        JTRutaCertificado.setNextFocusableComponent(JTRutaKey);
        PNLCampos.add(JTRutaCertificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 85, 300, -1));

        JRBMoral.setSelected(true);
        JRBMoral.setText("Moral");
        JRBMoral.setNextFocusableComponent(JRBFisica);
        PNLCampos.add(JRBMoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 10, -1, 20));

        JRBFisica.setText("Física");
        PNLCampos.add(JRBFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 10, -1, 20));

        JRBPEPS.setSelected(true);
        JRBPEPS.setText("PEPS");
        JRBPEPS.setNextFocusableComponent(JRBUEPS);
        PNLCampos.add(JRBPEPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 278, -1, -1));

        JRBUEPS.setText("UEPS");
        JRBUEPS.setNextFocusableComponent(JRBUltCost);
        PNLCampos.add(JRBUEPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 304, -1, -1));

        JRBUltCost.setText("Ult Cost");
        JRBUltCost.setNextFocusableComponent(JRBPromedio);
        PNLCampos.add(JRBUltCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 327, -1, -1));

        JRBPromedio.setText("Promedio");
        JRBPromedio.setNextFocusableComponent(BTNLimpiarCampos);
        PNLCampos.add(JRBPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 350, -1, -1));

        jLabel30.setText("Ext");
        PNLCampos.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 140, -1, -1));

        JTExtTel.setNextFocusableComponent(JTCalle);
        PNLCampos.add(JTExtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 137, 53, -1));

        jLabel33.setText("Plantilla");
        PNLCampos.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 192, 105, -1));

        JTPlantilla.setNextFocusableComponent(JTFechaAlta);
        PNLCampos.add(JTPlantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 192, 300, -1));

        BTNLimpiarCampos.setBackground(new java.awt.Color(255, 255, 255));
        BTNLimpiarCampos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNLimpiarCampos.setForeground(new java.awt.Color(0, 102, 0));
        BTNLimpiarCampos.setText("Limpiar Campos");
        BTNLimpiarCampos.setAutoscrolls(true);
        BTNLimpiarCampos.setNextFocusableComponent(BTNNuevaEmpresa);
        BTNLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLimpiarCamposActionPerformed(evt);
            }
        });

        BTNNuevaEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        BTNNuevaEmpresa.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNNuevaEmpresa.setForeground(new java.awt.Color(0, 102, 0));
        BTNNuevaEmpresa.setText("Agregar Empresa");
        BTNNuevaEmpresa.setNextFocusableComponent(BTNActualiza);
        BTNNuevaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNNuevaEmpresaActionPerformed(evt);
            }
        });

        BTNActualiza.setBackground(new java.awt.Color(255, 255, 255));
        BTNActualiza.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNActualiza.setForeground(new java.awt.Color(0, 102, 0));
        BTNActualiza.setText("Actualizar");
        BTNActualiza.setNextFocusableComponent(BTNBorraPorId);
        BTNActualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNActualizaActionPerformed(evt);
            }
        });

        BTNBorraPorId.setBackground(new java.awt.Color(255, 255, 255));
        BTNBorraPorId.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNBorraPorId.setForeground(new java.awt.Color(0, 102, 0));
        BTNBorraPorId.setText("Borrar");
        BTNBorraPorId.setNextFocusableComponent(BTNRespalda);
        BTNBorraPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBorraPorIdActionPerformed(evt);
            }
        });

        BTNRespalda.setBackground(new java.awt.Color(255, 255, 255));
        BTNRespalda.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNRespalda.setForeground(new java.awt.Color(0, 102, 0));
        BTNRespalda.setText("Respaldar");
        BTNRespalda.setNextFocusableComponent(BTNRestaura);
        BTNRespalda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRespaldaActionPerformed(evt);
            }
        });

        BTNRestaura.setBackground(new java.awt.Color(255, 255, 255));
        BTNRestaura.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNRestaura.setForeground(new java.awt.Color(0, 102, 0));
        BTNRestaura.setText("Restaura");
        BTNRestaura.setNextFocusableComponent(JTIdEmpresa);

        javax.swing.GroupLayout PNLAccionesLayout = new javax.swing.GroupLayout(PNLAcciones);
        PNLAcciones.setLayout(PNLAccionesLayout);
        PNLAccionesLayout.setHorizontalGroup(
            PNLAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNLimpiarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNNuevaEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNActualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNBorraPorId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNRespalda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNRestaura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNLAccionesLayout.setVerticalGroup(
            PNLAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLAccionesLayout.createSequentialGroup()
                .addComponent(BTNLimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNNuevaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNActualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNBorraPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNRespalda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNRestaura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        PNLCampos.add(PNLAcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 66, -1, -1));

        BTNCargaRegimenFiscal.setText("jButton2");
        BTNCargaRegimenFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCargaRegimenFiscalActionPerformed(evt);
            }
        });
        PNLCampos.add(BTNCargaRegimenFiscal, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 59, 29, 20));

        BTNCargaCDS.setText("jButton3");
        BTNCargaCDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCargaCDSActionPerformed(evt);
            }
        });
        PNLCampos.add(BTNCargaCDS, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 85, 29, 20));

        BTNCargaLugarExpedicion.setText("jButton4");
        BTNCargaLugarExpedicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCargaLugarExpedicionActionPerformed(evt);
            }
        });
        PNLCampos.add(BTNCargaLugarExpedicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 33, 29, 20));

        BTNCargaKey.setText("jButton5");
        BTNCargaKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCargaKeyActionPerformed(evt);
            }
        });
        PNLCampos.add(BTNCargaKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 111, 29, 20));

        BTNPruebaPW.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNPruebaPW.setText("Probar");
        BTNPruebaPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPruebaPWActionPerformed(evt);
            }
        });
        PNLCampos.add(BTNPruebaPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 137, -1, -1));
        PNLCampos.add(JTPasswordCertificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 138, 246, -1));

        btnRutaAplicacion.setText("jButton1");
        btnRutaAplicacion.setName(""); // NOI18N
        btnRutaAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaAplicacionActionPerformed(evt);
            }
        });
        PNLCampos.add(btnRutaAplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 166, 29, 20));

        BTNPlantilla.setText("jButton1");
        BTNPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPlantillaActionPerformed(evt);
            }
        });
        PNLCampos.add(BTNPlantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 192, 29, 20));

        BTNCargaPais.setText("jButton1");
        BTNCargaPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCargaPaisActionPerformed(evt);
            }
        });
        PNLCampos.add(BTNCargaPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 325, 29, 20));

        BTNCodigoPostal.setText("jButton1");
        BTNCodigoPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCodigoPostalActionPerformed(evt);
            }
        });
        PNLCampos.add(BTNCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 305, 29, 20));

        jPanImg1.setBackground(new java.awt.Color(255, 255, 204));
        jPanImg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanImg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanImg1MouseExited(evt);
            }
        });
        jPanImg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanImg1KeyPressed(evt);
            }
        });
        jPanImg1.setLayout(new java.awt.BorderLayout());
        jPanImg1.add(jLImg, java.awt.BorderLayout.CENTER);

        PNLCampos.add(jPanImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 299, 140, 90));

        jLabel5.setText("Logotipo");
        PNLCampos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 279, -1, -1));

        jBCargImg.setBackground(new java.awt.Color(255, 255, 255));
        jBCargImg.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jBCargImg.setText("Cargar");
        jBCargImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBCargImgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBCargImgMouseExited(evt);
            }
        });
        jBCargImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCargImgActionPerformed(evt);
            }
        });
        jBCargImg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBCargImgKeyPressed(evt);
            }
        });
        PNLCampos.add(jBCargImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 395, 70, 30));

        jBDelImg.setBackground(new java.awt.Color(255, 255, 255));
        jBDelImg.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jBDelImg.setText("Borrar");
        jBDelImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBDelImgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBDelImgMouseExited(evt);
            }
        });
        jBDelImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDelImgActionPerformed(evt);
            }
        });
        PNLCampos.add(jBDelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 395, 70, 30));

        JPTabla.setAutoscrolls(true);
        JPTabla.setPreferredSize(new java.awt.Dimension(1000, 400));

        jTabEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTabEmpresas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTabEmpresas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JPTabla.setViewportView(jTabEmpresas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PNLCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(PNLBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JPTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(JPTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PNLCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PNLBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPTabla.getAccessibleContext().setAccessibleParent(JPTabla);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNBorraPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBorraPorIdActionPerformed
                
    }//GEN-LAST:event_BTNBorraPorIdActionPerformed

    private void BTNActualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNActualizaActionPerformed
                
    }//GEN-LAST:event_BTNActualizaActionPerformed
       
    private void BTNNuevaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNNuevaEmpresaActionPerformed
                
    }//GEN-LAST:event_BTNNuevaEmpresaActionPerformed

    private void JTFechaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFechaAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFechaAltaActionPerformed

    private void BTNLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLimpiarCamposActionPerformed
        
    }//GEN-LAST:event_BTNLimpiarCamposActionPerformed

    private void BTNRespaldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRespaldaActionPerformed
        
    }//GEN-LAST:event_BTNRespaldaActionPerformed

    private void BTNCargaLugarExpedicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCargaLugarExpedicionActionPerformed
        
    }//GEN-LAST:event_BTNCargaLugarExpedicionActionPerformed

    private void BTNCargaRegimenFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCargaRegimenFiscalActionPerformed
        
    }//GEN-LAST:event_BTNCargaRegimenFiscalActionPerformed

    private void BTNCargaCDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCargaCDSActionPerformed
        
    }//GEN-LAST:event_BTNCargaCDSActionPerformed

    private void BTNCargaKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCargaKeyActionPerformed
        
    }//GEN-LAST:event_BTNCargaKeyActionPerformed

    private void BTNPruebaPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPruebaPWActionPerformed
        
        
    }//GEN-LAST:event_BTNPruebaPWActionPerformed

    private void BTNCodigoPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCodigoPostalActionPerformed
        
    }//GEN-LAST:event_BTNCodigoPostalActionPerformed

    private void BTNCargaPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCargaPaisActionPerformed
        
    }//GEN-LAST:event_BTNCargaPaisActionPerformed

    private void btnRutaAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaAplicacionActionPerformed
        
    }//GEN-LAST:event_btnRutaAplicacionActionPerformed

    private void BTNPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPlantillaActionPerformed
        
    }//GEN-LAST:event_BTNPlantillaActionPerformed

    private void jPanImg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanImg1MouseEntered
        
    }//GEN-LAST:event_jPanImg1MouseEntered

    private void jPanImg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanImg1MouseExited

    }//GEN-LAST:event_jPanImg1MouseExited

    private void jPanImg1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanImg1KeyPressed

    }//GEN-LAST:event_jPanImg1KeyPressed

    private void jBCargImgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCargImgMouseEntered
        
    }//GEN-LAST:event_jBCargImgMouseEntered

    private void jBCargImgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCargImgMouseExited
        
    }//GEN-LAST:event_jBCargImgMouseExited

    private void jBCargImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCargImgActionPerformed

    }//GEN-LAST:event_jBCargImgActionPerformed

    private void jBCargImgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBCargImgKeyPressed

    }//GEN-LAST:event_jBCargImgKeyPressed

    private void jBDelImgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDelImgMouseEntered
        
    }//GEN-LAST:event_jBDelImgMouseEntered

    private void jBDelImgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDelImgMouseExited
        
    }//GEN-LAST:event_jBDelImgMouseExited

    private void jBDelImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDelImgActionPerformed
        
    }//GEN-LAST:event_jBDelImgActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton BTNActualiza;
    protected javax.swing.JButton BTNBorraPorId;
    protected javax.swing.JButton BTNCargaCDS;
    protected javax.swing.JButton BTNCargaKey;
    protected javax.swing.JButton BTNCargaLugarExpedicion;
    protected javax.swing.JButton BTNCargaPais;
    protected javax.swing.JButton BTNCargaRegimenFiscal;
    protected javax.swing.JButton BTNCodigoPostal;
    protected javax.swing.JButton BTNLimpiarCampos;
    protected javax.swing.JButton BTNNuevaEmpresa;
    protected javax.swing.JButton BTNPlantilla;
    protected javax.swing.JButton BTNPruebaPW;
    protected javax.swing.JButton BTNRespalda;
    protected javax.swing.JButton BTNRestaura;
    protected javax.swing.JScrollPane JPTabla;
    protected javax.swing.JRadioButton JRBFisica;
    protected javax.swing.JRadioButton JRBMoral;
    protected javax.swing.JRadioButton JRBPEPS;
    protected javax.swing.JRadioButton JRBPromedio;
    protected javax.swing.JRadioButton JRBUEPS;
    protected javax.swing.JRadioButton JRBUltCost;
    protected javax.swing.JTextField JTBaseDeDatos;
    protected javax.swing.JTextField JTCP;
    protected javax.swing.JTextField JTCalle;
    protected javax.swing.JTextField JTCiudad;
    protected javax.swing.JTextField JTCodigoEmpresa;
    protected javax.swing.JTextField JTColonia;
    protected javax.swing.JTextField JTCorreoElectronico;
    protected javax.swing.JTextField JTEmpresa;
    protected javax.swing.JTextField JTEstado;
    protected javax.swing.JTextField JTExtTel;
    protected javax.swing.JTextField JTFechaAlta;
    protected javax.swing.JTextField JTFechaModificacion;
    protected javax.swing.JTextField JTIdEmpresa;
    protected javax.swing.JTextField JTLugarDeExpedicion;
    protected javax.swing.JTextField JTNoExt;
    protected javax.swing.JTextField JTNoInt;
    protected javax.swing.JTextField JTPais;
    protected javax.swing.JPasswordField JTPasswordCertificado;
    protected javax.swing.JTextField JTPlantilla;
    protected javax.swing.JTextField JTRFC;
    protected javax.swing.JTextField JTRegimenFiscal;
    protected javax.swing.JTextField JTRutaAplicacion;
    protected javax.swing.JTextField JTRutaCertificado;
    protected javax.swing.JTextField JTRutaKey;
    protected javax.swing.JTextField JTSitioWeb;
    protected javax.swing.JTextField JTTelefono;
    private javax.swing.JPanel PNLAcciones;
    private javax.swing.JPanel PNLBusqueda;
    private javax.swing.JPanel PNLCampos;
    protected javax.swing.JButton btnRutaAplicacion;
    protected javax.swing.JButton jBCargImg;
    protected javax.swing.JButton jBDelImg;
    protected javax.swing.JLabel jLImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    protected javax.swing.JPanel jPanImg1;
    protected com.era.views.tables.BasDatsTable jTabEmpresas;
    // End of variables declaration//GEN-END:variables
}
