package com.era.views;


public abstract class FormPagoJFrame extends BaseJFrame  {
        
    protected FormPagoJFrame(final String idTextTitleWindow) {
        
        super(idTextTitleWindow);
        
        initComponents();
        
        postInitComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLblCliente = new javax.swing.JLabel();
        txtCustomerCode = new javax.swing.JTextField();
        jBAbon = new javax.swing.JButton();
        jCTimbrar = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jForImporte = new javax.swing.JFormattedTextField();
        jCImprimir = new javax.swing.JCheckBox();
        txtCustomerName = new javax.swing.JTextField();
        jBBancos = new javax.swing.JButton();
        jTBanco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTConcep = new javax.swing.JTextField();
        jBConcep = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTFormPag = new javax.swing.JTextField();
        jBFormPag = new javax.swing.JButton();
        labelPendingToPay = new javax.swing.JLabel();
        jTFolBanc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTComentario = new javax.swing.JTextField();
        txtFormPagDescrip = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblCliente.setText("Cliente:");
        jPanel1.add(jLblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 14, -1, -1));

        txtCustomerCode.setEditable(false);
        jPanel1.add(txtCustomerCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 52, -1));

        jBAbon.setBackground(new java.awt.Color(255, 255, 255));
        jBAbon.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBAbon.setForeground(new java.awt.Color(0, 102, 0));
        jBAbon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/abona.png"))); // NOI18N
        jBAbon.setText("Abonar");
        jBAbon.setToolTipText("Abonar a Venta");
        jBAbon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jBAbon, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 120, 30));

        jCTimbrar.setText("Timbrar");
        jPanel1.add(jCTimbrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Importe:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 39, 110, -1));
        jLabel4.getAccessibleContext().setAccessibleName("Importe $");

        jPanel1.add(jForImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 38, 100, -1));

        jCImprimir.setText("Imprimir Ticket");
        jPanel1.add(jCImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        txtCustomerName.setEditable(false);
        jPanel1.add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 290, -1));

        jBBancos.setBackground(new java.awt.Color(255, 255, 255));
        jBBancos.setText("jButton1");
        jBBancos.setToolTipText("Buscar concepto");
        jPanel1.add(jBBancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 20, 20));

        jTBanco.setEditable(false);
        jTBanco.setToolTipText("Concepto del pago del abono");
        jTBanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel1.add(jTBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 151, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cuenta Bancaria:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Concepto:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, -1));

        jTConcep.setEditable(false);
        jTConcep.setToolTipText("Concepto del pago del abono");
        jTConcep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel1.add(jTConcep, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 151, 20));

        jBConcep.setBackground(new java.awt.Color(255, 255, 255));
        jBConcep.setText("jButton1");
        jBConcep.setToolTipText("Buscar concepto");
        jPanel1.add(jBConcep, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 20, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Método de pago:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, -1));

        jTFormPag.setEditable(false);
        jTFormPag.setToolTipText("Forma de pago del abono");
        jTFormPag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel1.add(jTFormPag, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 151, 20));

        jBFormPag.setBackground(new java.awt.Color(255, 255, 255));
        jBFormPag.setText("jButton1");
        jBFormPag.setToolTipText("Buscar forma de pago");
        jPanel1.add(jBFormPag, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 20, 20));

        labelPendingToPay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPendingToPay.setForeground(new java.awt.Color(0, 153, 51));
        labelPendingToPay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelPendingToPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 100, -1));

        jTFolBanc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel1.add(jTFolBanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 244, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Comentario:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 120, -1));

        jTComentario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel1.add(jTComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 244, 20));

        txtFormPagDescrip.setEditable(false);
        txtFormPagDescrip.setToolTipText("Forma de pago del abono");
        txtFormPagDescrip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel1.add(txtFormPagDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 151, 151, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Pendiente por liquidar:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 170, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Folio de banco:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jBAbon;
    protected javax.swing.JButton jBBancos;
    protected javax.swing.JButton jBConcep;
    protected javax.swing.JButton jBFormPag;
    protected javax.swing.JCheckBox jCImprimir;
    protected javax.swing.JCheckBox jCTimbrar;
    private javax.swing.JCheckBox jCheckBox1;
    protected javax.swing.JFormattedTextField jForImporte;
    protected javax.swing.JLabel jLabel11;
    protected javax.swing.JLabel jLabel13;
    protected javax.swing.JLabel jLabel14;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JLabel jLabel4;
    protected javax.swing.JLabel jLabel7;
    protected javax.swing.JLabel jLabel9;
    protected javax.swing.JLabel jLblCliente;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JTextField jTBanco;
    protected javax.swing.JTextField jTComentario;
    protected javax.swing.JTextField jTConcep;
    protected javax.swing.JTextField jTFolBanc;
    protected javax.swing.JTextField jTFormPag;
    protected javax.swing.JLabel labelPendingToPay;
    protected javax.swing.JTextField txtCustomerCode;
    protected javax.swing.JTextField txtCustomerName;
    protected javax.swing.JTextField txtFormPagDescrip;
    // End of variables declaration//GEN-END:variables
}
