package com.era.views;

/**
 *
 * @author augus
 */
public abstract class ListadoPagosJFrame extends BaseJFrame {
    
    
    public ListadoPagosJFrame(final String idTextTitleWindow) {
        
        super(idTextTitleWindow);
        
        initComponents();
    
        //Post inicialization
        postInitComponents();                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabPagos = new javax.swing.JTable();
        jBBusc = new javax.swing.JButton();
        jTBusc = new javax.swing.JTextField();
        jBMosT = new javax.swing.JButton();
        jBGenPDF = new javax.swing.JButton();
        jBCa = new javax.swing.JButton();
        jButtonTimbrar = new javax.swing.JButton();
        jBSal = new javax.swing.JButton();
        jBAbon = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabPartidas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBCarpetaPagos = new javax.swing.JButton();
        jBEnvCorr = new javax.swing.JButton();
        jBPDF = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();
        jBGenPDF1 = new javax.swing.JButton();
        jBVerTicket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de pagos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Fecha", "Serie", "Folio", "Cliente", "Total", "Pendiente", "Estado", "UUID", "Id", "Color"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabPagos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTabPagos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTabPagos.getTableHeader().setResizingAllowed(false);
        jTabPagos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTabPagos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 44, 650, 138));

        jBBusc.setBackground(new java.awt.Color(255, 255, 255));
        jBBusc.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBBusc.setForeground(new java.awt.Color(0, 102, 0));
        jBBusc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/busc5.png"))); // NOI18N
        jBBusc.setText("Buscar F3");
        jPanel1.add(jBBusc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 183, 112, 19));

        jTBusc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel1.add(jTBusc, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 182, 399, 20));

        jBMosT.setBackground(new java.awt.Color(255, 255, 255));
        jBMosT.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBMosT.setForeground(new java.awt.Color(0, 102, 0));
        jBMosT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/mostt.png"))); // NOI18N
        jBMosT.setText("Mostrar F4");
        jBMosT.setToolTipText("Mostrar nuevamente todos los Registros");
        jPanel1.add(jBMosT, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 182, 139, 20));

        jBGenPDF.setBackground(new java.awt.Color(255, 255, 255));
        jBGenPDF.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBGenPDF.setForeground(new java.awt.Color(0, 102, 0));
        jBGenPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/genpdf.png"))); // NOI18N
        jBGenPDF.setText("Generar PDF");
        jBGenPDF.setToolTipText("Generar PDF de venta");
        jBGenPDF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jBGenPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 146, 30));

        jBCa.setBackground(new java.awt.Color(255, 255, 255));
        jBCa.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBCa.setForeground(new java.awt.Color(0, 102, 0));
        jBCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/can.png"))); // NOI18N
        jBCa.setText("Cancelar");
        jBCa.setToolTipText("Cancelar venta(s) (Ctrl+SUPR)");
        jBCa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jBCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 146, 30));

        jButtonTimbrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTimbrar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonTimbrar.setForeground(new java.awt.Color(0, 102, 0));
        jButtonTimbrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cfdtim.png"))); // NOI18N
        jButtonTimbrar.setText("Timbrar");
        jButtonTimbrar.setToolTipText("Timbrar factura(s)");
        jButtonTimbrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonTimbrar.setName(""); // NOI18N
        jPanel1.add(jButtonTimbrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 146, 30));

        jBSal.setBackground(new java.awt.Color(255, 255, 255));
        jBSal.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBSal.setForeground(new java.awt.Color(0, 102, 0));
        jBSal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/sal.png"))); // NOI18N
        jBSal.setText("Salir");
        jBSal.setToolTipText("Salir (ESC)");
        jBSal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jBSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 146, 30));

        jBAbon.setBackground(new java.awt.Color(255, 255, 255));
        jBAbon.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBAbon.setForeground(new java.awt.Color(0, 102, 0));
        jBAbon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/abona.png"))); // NOI18N
        jBAbon.setText("Abonar");
        jBAbon.setToolTipText("Abonar a Venta");
        jBAbon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jBAbon, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 146, 30));

        jTabPartidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Fecha", "Serie", "Folio", "Cliente", "Total", "Pendiente", "Estado", "UUID"
            }
        ));
        jScrollPane2.setViewportView(jTabPartidas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 650, 138));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Cliente:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 373, 27));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 11, 107, 27));

        jBCarpetaPagos.setBackground(new java.awt.Color(255, 255, 255));
        jBCarpetaPagos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBCarpetaPagos.setForeground(new java.awt.Color(0, 102, 0));
        jBCarpetaPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/dir.png"))); // NOI18N
        jBCarpetaPagos.setText("Pagos");
        jBCarpetaPagos.setToolTipText("Salir (ESC)");
        jBCarpetaPagos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jBCarpetaPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 146, 30));

        jBEnvCorr.setBackground(new java.awt.Color(255, 255, 255));
        jBEnvCorr.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBEnvCorr.setForeground(new java.awt.Color(0, 102, 0));
        jBEnvCorr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/corrs.png"))); // NOI18N
        jBEnvCorr.setText("Enviar");
        jBEnvCorr.setToolTipText("Enviar por correo");
        jBEnvCorr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jBEnvCorr, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 146, 30));

        jBPDF.setBackground(new java.awt.Color(255, 255, 255));
        jBPDF.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBPDF.setForeground(new java.awt.Color(0, 102, 0));
        jBPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pdf.png"))); // NOI18N
        jBPDF.setText("Ver PDF");
        jBPDF.setToolTipText("Ver PDF (Alt+F)");
        jBPDF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jBPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 146, 30));

        jBActualizar.setBackground(new java.awt.Color(255, 255, 255));
        jBActualizar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBActualizar.setForeground(new java.awt.Color(0, 102, 0));
        jBActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/actualizar.png"))); // NOI18N
        jBActualizar.setText("Actualizar");
        jBActualizar.setToolTipText("Actualizar");
        jBActualizar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jBActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 146, 30));

        jBGenPDF1.setBackground(new java.awt.Color(255, 255, 255));
        jBGenPDF1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBGenPDF1.setForeground(new java.awt.Color(0, 102, 0));
        jBGenPDF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/impres.png"))); // NOI18N
        jBGenPDF1.setText("Imprimir Ticket");
        jBGenPDF1.setToolTipText("Generar PDF de venta");
        jBGenPDF1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jBGenPDF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 146, 30));

        jBVerTicket.setBackground(new java.awt.Color(255, 255, 255));
        jBVerTicket.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBVerTicket.setForeground(new java.awt.Color(0, 102, 0));
        jBVerTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ojo.gif"))); // NOI18N
        jBVerTicket.setText("Ver Ticket");
        jBVerTicket.setToolTipText("Salir (ESC)");
        jBVerTicket.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jBVerTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 146, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jBAbon;
    protected javax.swing.JButton jBActualizar;
    protected javax.swing.JButton jBBusc;
    protected javax.swing.JButton jBCa;
    protected javax.swing.JButton jBCarpetaPagos;
    protected javax.swing.JButton jBEnvCorr;
    protected javax.swing.JButton jBGenPDF;
    protected javax.swing.JButton jBGenPDF1;
    protected javax.swing.JButton jBMosT;
    protected javax.swing.JButton jBPDF;
    protected javax.swing.JButton jBSal;
    protected javax.swing.JButton jBVerTicket;
    protected javax.swing.JButton jButtonTimbrar;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JScrollPane jScrollPane2;
    protected javax.swing.JTextField jTBusc;
    private javax.swing.JTable jTabPagos;
    private javax.swing.JTable jTabPartidas;
    // End of variables declaration//GEN-END:variables
}
