/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.era.views;

/**
 *
 * @author PC
 */
public class RegisterWebsiteJFrame extends javax.swing.JFrame {
    
    private OnURLLabelClicked OnURLLabelClicked;
    private OnOKButtonClicked OnOKButtonClicked;
    
    /**
     * Creates new form RegisterWebsiteJFrame
     */
    public RegisterWebsiteJFrame() {
        
        super("");
        
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    public OnURLLabelClicked getOnURLLabelClicked() {
        return OnURLLabelClicked;
    }

    public void setOnURLLabelClicked(OnURLLabelClicked OnURLLabelClicked) {
        this.OnURLLabelClicked = OnURLLabelClicked;
    }

    public OnOKButtonClicked getOnOKButtonClicked() {
        return OnOKButtonClicked;
    }

    public void setOnOKButtonClicked(OnOKButtonClicked OnOKButtonClicked) {
        this.OnOKButtonClicked = OnOKButtonClicked;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        OKjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        urlJLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OKjButton.setText("OK");
        OKjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(OKjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 68, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Si aun no te has registrado en el sitio de ERA, en el siguiente enlace podrás hacerlo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        urlJLabel.setForeground(new java.awt.Color(51, 0, 153));
        urlJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        urlJLabel.setText("www.easyretail.com.mx");
        urlJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        urlJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urlJLabelMouseClicked(evt);
            }
        });
        jPanel1.add(urlJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 360, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, 20));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKjButtonActionPerformed
        
        if(OnOKButtonClicked!=null){
            OnOKButtonClicked.onClicked(evt);
        }
        
    }//GEN-LAST:event_OKjButtonActionPerformed

    private void urlJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urlJLabelMouseClicked
        
        if(OnURLLabelClicked!=null){
            OnURLLabelClicked.onClicked(evt);
        }
        
    }//GEN-LAST:event_urlJLabelMouseClicked
            
    public interface OnURLLabelClicked{
        public void onClicked(java.awt.event.MouseEvent evt);
    }
    
    public interface OnOKButtonClicked{
        public void onClicked(java.awt.event.ActionEvent evt);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel urlJLabel;
    // End of variables declaration//GEN-END:variables
}
