/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.era.views;

/**
 *
 * @author PC
 */
public abstract class VtasJFrame extends BaseJFrame {

    public VtasJFrame(final String idTextTitleWindow){
        
        super(idTextTitleWindow);
        
        initComponents();
        
        postInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVentas = new com.era.views.tables.SalesTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTab2 = new com.era.views.tables.PartvtaTable();
        jLabel4 = new java.awt.Label();
        jRadioBoxTipoDeVentas = new com.era.views.comboboxes.DocumentOriginCombobox();
        jLabelTipDoc = new java.awt.Label();
        jBBusc = new java.awt.Button();
        jTBusc = new java.awt.TextField();
        jBMosT = new java.awt.Button();
        jLabel5 = new java.awt.Label();
        label_total = new java.awt.Label();
        jLabelPagination = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemGralNew = new javax.swing.JMenuItem();
        jMenuItemGralView = new javax.swing.JMenuItem();
        jMenuItemGralSend = new javax.swing.JMenuItem();
        jMenuItemGralViewPDF = new javax.swing.JMenuItem();
        jMenuItemGralGeneratePDF = new javax.swing.JMenuItem();
        jMenuItemGralCancel = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemSalesDev = new javax.swing.JMenuItem();
        jMenuItemSalesDevP = new javax.swing.JMenuItem();
        jMenuItemSalesFacTick = new javax.swing.JMenuItem();
        jMenuItemTicketsFacturados = new javax.swing.JMenuItem();
        jMenuItemInvoicesNotRinged = new javax.swing.JMenuItem();
        jMenuDocuSAT = new javax.swing.JMenu();
        jMenuItemDocuSatCheck = new javax.swing.JMenuItem();
        jMenuItemDocuSatRing = new javax.swing.JMenuItem();
        jMenuItemDocuSatAcuse = new javax.swing.JMenuItem();
        jMenuItemGetXML = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemFoldersRems = new javax.swing.JMenuItem();
        jMenuItemFoldersCortX = new javax.swing.JMenuItem();
        jMenuItemFoldersCortZ = new javax.swing.JMenuItem();
        jMenuItemFoldersCreditNot = new javax.swing.JMenuItem();
        jMenuItemFoldersCFDI = new javax.swing.JMenuItem();
        jMenuItemFoldersTicks = new javax.swing.JMenuItem();
        jMenuItemFoldersCancels = new javax.swing.JMenuItem();
        jMenuItemFoldersDevs = new javax.swing.JMenuItem();
        jMenuItemFoldersDevsP = new javax.swing.JMenuItem();
        jMenuItemFoldersAcuses = new javax.swing.JMenuItem();
        jMenuItemDocuSatGetXML = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(100, 100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableVentas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1200, 209));

        jTab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTab2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1200, 210));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Ventas:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 11, 70, 20));
        jPanel1.add(jRadioBoxTipoDeVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, 20));

        jLabelTipDoc.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel1.add(jLabelTipDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 11, 170, -1));

        jBBusc.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBBusc.setForeground(new java.awt.Color(0, 102, 0));
        jBBusc.setLabel("Buscar F3");
        jPanel1.add(jBBusc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 96, -1));
        jPanel1.add(jTBusc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 990, -1));

        jBMosT.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBMosT.setForeground(new java.awt.Color(0, 102, 0));
        jBMosT.setLabel("Mostrar F4");
        jPanel1.add(jBMosT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 250, 96, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("Partidas:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 84, -1));

        label_total.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label_total.setText("# Ventas y total:");
        jPanel1.add(label_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 120, 20));
        jPanel1.add(jLabelPagination, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 350, 20));

        jMenu1.setText("General");

        jMenuItemGralNew.setText("Nueva");
        jMenu1.add(jMenuItemGralNew);

        jMenuItemGralView.setText("Ver");
        jMenu1.add(jMenuItemGralView);

        jMenuItemGralSend.setText("Enviar");
        jMenu1.add(jMenuItemGralSend);

        jMenuItemGralViewPDF.setText("Ver PDF");
        jMenu1.add(jMenuItemGralViewPDF);

        jMenuItemGralGeneratePDF.setText("Generar PDF");
        jMenu1.add(jMenuItemGralGeneratePDF);

        jMenuItemGralCancel.setText("Cancelar");
        jMenu1.add(jMenuItemGralCancel);

        jMenuItemExit.setText("Salir");
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ventas");

        jMenuItemSalesDev.setText("Devolución");
        jMenu2.add(jMenuItemSalesDev);

        jMenuItemSalesDevP.setText("Dev.Parcial");
        jMenu2.add(jMenuItemSalesDevP);

        jMenuItemSalesFacTick.setText("Facturar Tickets");
        jMenu2.add(jMenuItemSalesFacTick);

        jMenuItemTicketsFacturados.setText("Ticket Facturados");
        jMenu2.add(jMenuItemTicketsFacturados);

        jMenuItemInvoicesNotRinged.setText("Facturas no Timbradas");
        jMenu2.add(jMenuItemInvoicesNotRinged);

        jMenuBar1.add(jMenu2);

        jMenuDocuSAT.setText("Documentos SAT");

        jMenuItemDocuSatCheck.setText("Comprobar");
        jMenuDocuSAT.add(jMenuItemDocuSatCheck);

        jMenuItemDocuSatRing.setText("Timbrar");
        jMenuDocuSAT.add(jMenuItemDocuSatRing);

        jMenuItemDocuSatAcuse.setText("Acuse");
        jMenuDocuSAT.add(jMenuItemDocuSatAcuse);

        jMenuItemGetXML.setText("Obtener XML");
        jMenuDocuSAT.add(jMenuItemGetXML);

        jMenuBar1.add(jMenuDocuSAT);

        jMenu5.setText("Folder");

        jMenuItemFoldersRems.setText("Remisiones");
        jMenu5.add(jMenuItemFoldersRems);

        jMenuItemFoldersCortX.setText("Cortes X");
        jMenu5.add(jMenuItemFoldersCortX);

        jMenuItemFoldersCortZ.setText("Cortes Z");
        jMenu5.add(jMenuItemFoldersCortZ);

        jMenuItemFoldersCreditNot.setText("Notas de Crédito");
        jMenu5.add(jMenuItemFoldersCreditNot);

        jMenuItemFoldersCFDI.setText("CFDI");
        jMenu5.add(jMenuItemFoldersCFDI);

        jMenuItemFoldersTicks.setText("Tickets");
        jMenu5.add(jMenuItemFoldersTicks);

        jMenuItemFoldersCancels.setText("Cancelados");
        jMenu5.add(jMenuItemFoldersCancels);

        jMenuItemFoldersDevs.setText("Devoluciones");
        jMenu5.add(jMenuItemFoldersDevs);

        jMenuItemFoldersDevsP.setText("Dev. Parciales");
        jMenu5.add(jMenuItemFoldersDevsP);

        jMenuItemFoldersAcuses.setText("Acuses");
        jMenu5.add(jMenuItemFoldersAcuses);

        jMenuItemDocuSatGetXML.setText("Obtener XML");
        jMenu5.add(jMenuItemDocuSatGetXML);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1227, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected java.awt.Button jBBusc;
    protected java.awt.Button jBMosT;
    protected java.awt.Label jLabel4;
    protected java.awt.Label jLabel5;
    protected javax.swing.JLabel jLabelPagination;
    protected java.awt.Label jLabelTipDoc;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    protected javax.swing.JMenu jMenuDocuSAT;
    private javax.swing.JMenuItem jMenuItem1;
    protected javax.swing.JMenuItem jMenuItemDocuSatAcuse;
    protected javax.swing.JMenuItem jMenuItemDocuSatCheck;
    protected javax.swing.JMenuItem jMenuItemDocuSatGetXML;
    protected javax.swing.JMenuItem jMenuItemDocuSatRing;
    protected javax.swing.JMenuItem jMenuItemExit;
    protected javax.swing.JMenuItem jMenuItemFoldersAcuses;
    protected javax.swing.JMenuItem jMenuItemFoldersCFDI;
    protected javax.swing.JMenuItem jMenuItemFoldersCancels;
    protected javax.swing.JMenuItem jMenuItemFoldersCortX;
    protected javax.swing.JMenuItem jMenuItemFoldersCortZ;
    protected javax.swing.JMenuItem jMenuItemFoldersCreditNot;
    protected javax.swing.JMenuItem jMenuItemFoldersDevs;
    protected javax.swing.JMenuItem jMenuItemFoldersDevsP;
    protected javax.swing.JMenuItem jMenuItemFoldersRems;
    protected javax.swing.JMenuItem jMenuItemFoldersTicks;
    protected javax.swing.JMenuItem jMenuItemGetXML;
    protected javax.swing.JMenuItem jMenuItemGralCancel;
    protected javax.swing.JMenuItem jMenuItemGralGeneratePDF;
    protected javax.swing.JMenuItem jMenuItemGralNew;
    protected javax.swing.JMenuItem jMenuItemGralSend;
    protected javax.swing.JMenuItem jMenuItemGralView;
    protected javax.swing.JMenuItem jMenuItemGralViewPDF;
    protected javax.swing.JMenuItem jMenuItemInvoicesNotRinged;
    protected javax.swing.JMenuItem jMenuItemSalesDev;
    protected javax.swing.JMenuItem jMenuItemSalesDevP;
    protected javax.swing.JMenuItem jMenuItemSalesFacTick;
    protected javax.swing.JMenuItem jMenuItemTicketsFacturados;
    private javax.swing.JPanel jPanel1;
    protected com.era.views.comboboxes.DocumentOriginCombobox jRadioBoxTipoDeVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    protected java.awt.TextField jTBusc;
    protected com.era.views.tables.PartvtaTable jTab2;
    protected com.era.views.tables.SalesTable jTableVentas;
    protected java.awt.Label label_total;
    // End of variables declaration//GEN-END:variables
}
